
import 'package:dogus_barber/utils/functions.dart';

String getPublicHolidayName(DateTime date) {
  // Convert date from "dd.mm.yyyy" to "yyyy-mm-dd"
  final dateString = firestoreString(date);
  final parts = dateString.split('.');
  final formattedDate = '${parts[2]}-${parts[1].padLeft(2, '0')}-${parts[0].padLeft(2, '0')}';

  for (var holiday in publicHolidays['feiertage']) {
    if (holiday['date'] == formattedDate) {
      return holiday['fname'] ?? 'Unknown Holiday';
    }
  }
  return 'Not a Holiday';
}

bool isPublicHoliday(DateTime date, String stateCode) {
  // Convert date from "dd.mm.yyyy" to "yyyy-mm-dd"
  final dateString = firestoreString(date);
  final parts = dateString.split('.');
  final formattedDate = '${parts[2]}-${parts[1].padLeft(2, '0')}-${parts[0].padLeft(2, '0')}';

  for (var holiday in publicHolidays['feiertage']) {
    if (holiday['date'] == formattedDate) {
      stateCode = stateCode.toLowerCase();
      return holiday['all_states'] == "1" || holiday[stateCode] == "1";
    }
  }
  return false; // Not a public holiday
}


// public holidays json
Map<String, dynamic> publicHolidays = {
  "status": "success",
  "feiertage": [
    {
      "date": "2024-01-01",
      "fname": "Neujahr",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2024-01-06",
      "fname": "Heilige Drei Könige",
      "all_states": "0",
      "bw": "1",
      "by": "1",
      "be": "0",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "0",
      "st": "1",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2024-03-08",
      "fname": "Internationaler Frauentag",
      "all_states": "0",
      "bw": "0",
      "by": "0",
      "be": "1",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "1",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2024-03-29",
      "fname": "Karfreitag",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2024-03-31",
      "fname": "Ostersonntag",
      "all_states": "0",
      "bw": "0",
      "by": "0",
      "be": "0",
      "bb": "1",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2024-04-01",
      "fname": "Ostermontag",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2024-05-01",
      "fname": "Tag der Arbeit",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2024-05-09",
      "fname": "Christi Himmelfahrt",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2024-05-19",
      "fname": "Pfingstsonntag",
      "all_states": "0",
      "bw": "0",
      "by": "0",
      "be": "0",
      "bb": "1",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2024-05-20",
      "fname": "Pfingstmontag",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2024-05-30",
      "fname": "Fronleichnam",
      "all_states": "0",
      "bw": "1",
      "by": "1",
      "be": "0",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "1",
      "mv": "0",
      "ni": "0",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2024-08-15",
      "fname": "Mariä Himmelfahrt",
      "all_states": "0",
      "bw": "0",
      "by": "1",
      "be": "0",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "1",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "Mariä Himmelfahrt ist in Gemeinden mit überwiegend katholischer Bevölkerung in Bayern ein gesetzlicher Feiertag.",
      "augsburg": null,
      "katholisch": "1"
    },
    {
      "date": "2024-09-20",
      "fname": "Weltkindertag",
      "all_states": "0",
      "bw": "0",
      "by": "0",
      "be": "0",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2024-10-03",
      "fname": "Tag der deutschen Einheit",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2024-10-31",
      "fname": "Reformationstag",
      "all_states": "0",
      "bw": "0",
      "by": "0",
      "be": "0",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "0",
      "mv": "1",
      "ni": "1",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2024-11-01",
      "fname": "Allerheiligen",
      "all_states": "0",
      "bw": "1",
      "by": "1",
      "be": "0",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2024-11-20",
      "fname": "Buß- und Bettag",
      "all_states": "0",
      "bw": "0",
      "by": "0",
      "be": "0",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "1",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2024-12-25",
      "fname": "1. Weihnachtstag",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2024-12-26",
      "fname": "2. Weihnachtstag",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2025-01-01",
      "fname": "Neujahr",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2025-01-06",
      "fname": "Heilige Drei Könige",
      "all_states": "0",
      "bw": "1",
      "by": "1",
      "be": "0",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "0",
      "st": "1",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2025-03-08",
      "fname": "Internationaler Frauentag",
      "all_states": "0",
      "bw": "0",
      "by": "0",
      "be": "1",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "1",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2025-04-18",
      "fname": "Karfreitag",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2025-04-20",
      "fname": "Ostersonntag",
      "all_states": "0",
      "bw": "0",
      "by": "0",
      "be": "0",
      "bb": "1",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2025-04-21",
      "fname": "Ostermontag",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2025-05-01",
      "fname": "Tag der Arbeit",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2025-05-29",
      "fname": "Christi Himmelfahrt",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2025-06-08",
      "fname": "Pfingstsonntag",
      "all_states": "0",
      "bw": "0",
      "by": "0",
      "be": "0",
      "bb": "1",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2025-06-09",
      "fname": "Pfingstmontag",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2025-06-19",
      "fname": "Fronleichnam",
      "all_states": "0",
      "bw": "1",
      "by": "1",
      "be": "0",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "1",
      "mv": "0",
      "ni": "0",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2025-08-15",
      "fname": "Mariä Himmelfahrt",
      "all_states": "0",
      "bw": "0",
      "by": "1",
      "be": "0",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "1",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "Mariä Himmelfahrt ist in Gemeinden mit überwiegend katholischer Bevölkerung in Bayern ein gesetzlicher Feiertag.",
      "augsburg": null,
      "katholisch": "1"
    },
    {
      "date": "2025-09-20",
      "fname": "Weltkindertag",
      "all_states": "0",
      "bw": "0",
      "by": "0",
      "be": "0",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2025-10-03",
      "fname": "Tag der deutschen Einheit",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2025-10-31",
      "fname": "Reformationstag",
      "all_states": "0",
      "bw": "0",
      "by": "0",
      "be": "0",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "0",
      "mv": "1",
      "ni": "1",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2025-11-01",
      "fname": "Allerheiligen",
      "all_states": "0",
      "bw": "1",
      "by": "1",
      "be": "0",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2025-11-19",
      "fname": "Buß- und Bettag",
      "all_states": "0",
      "bw": "0",
      "by": "0",
      "be": "0",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "1",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2025-12-25",
      "fname": "1. Weihnachtstag",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2025-12-26",
      "fname": "2. Weihnachtstag",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2026-01-01",
      "fname": "Neujahr",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2026-01-06",
      "fname": "Heilige Drei Könige",
      "all_states": "0",
      "bw": "1",
      "by": "1",
      "be": "0",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "0",
      "st": "1",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2026-03-08",
      "fname": "Internationaler Frauentag",
      "all_states": "0",
      "bw": "0",
      "by": "0",
      "be": "1",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "1",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2026-04-03",
      "fname": "Karfreitag",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2026-04-05",
      "fname": "Ostersonntag",
      "all_states": "0",
      "bw": "0",
      "by": "0",
      "be": "0",
      "bb": "1",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2026-04-06",
      "fname": "Ostermontag",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2026-05-01",
      "fname": "Tag der Arbeit",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2026-05-14",
      "fname": "Christi Himmelfahrt",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2026-05-24",
      "fname": "Pfingstsonntag",
      "all_states": "0",
      "bw": "0",
      "by": "0",
      "be": "0",
      "bb": "1",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2026-05-25",
      "fname": "Pfingstmontag",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2026-06-04",
      "fname": "Fronleichnam",
      "all_states": "0",
      "bw": "1",
      "by": "1",
      "be": "0",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "1",
      "mv": "0",
      "ni": "0",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2026-08-15",
      "fname": "Mariä Himmelfahrt",
      "all_states": "0",
      "bw": "0",
      "by": "1",
      "be": "0",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "1",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "Mariä Himmelfahrt ist in Gemeinden mit überwiegend katholischer Bevölkerung in Bayern ein gesetzlicher Feiertag.",
      "augsburg": null,
      "katholisch": "1"
    },
    {
      "date": "2026-09-20",
      "fname": "Weltkindertag",
      "all_states": "0",
      "bw": "0",
      "by": "0",
      "be": "0",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2026-10-03",
      "fname": "Tag der deutschen Einheit",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2026-10-31",
      "fname": "Reformationstag",
      "all_states": "0",
      "bw": "0",
      "by": "0",
      "be": "0",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "0",
      "mv": "1",
      "ni": "1",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2026-11-01",
      "fname": "Allerheiligen",
      "all_states": "0",
      "bw": "1",
      "by": "1",
      "be": "0",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "0",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2026-11-18",
      "fname": "Buß- und Bettag",
      "all_states": "0",
      "bw": "0",
      "by": "0",
      "be": "0",
      "bb": "0",
      "hb": "0",
      "hh": "0",
      "he": "0",
      "mv": "0",
      "ni": "0",
      "nw": "0",
      "rp": "0",
      "sl": "0",
      "sn": "1",
      "st": "0",
      "sh": "0",
      "th": "0",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2026-12-25",
      "fname": "1. Weihnachtstag",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    },
    {
      "date": "2026-12-26",
      "fname": "2. Weihnachtstag",
      "all_states": "1",
      "bw": "1",
      "by": "1",
      "be": "1",
      "bb": "1",
      "hb": "1",
      "hh": "1",
      "he": "1",
      "mv": "1",
      "ni": "1",
      "nw": "1",
      "rp": "1",
      "sl": "1",
      "sn": "1",
      "st": "1",
      "sh": "1",
      "th": "1",
      "comment": "",
      "augsburg": null,
      "katholisch": null
    }
  ]
};

